image: elypia/imagecaster:0.4.0-q8

stages:
  - test
  - build

cache:
  paths:
    - build/

test:
  stage: test
  script:
    - imagecaster check
  cache: {}

build:
  stage: build
  script:
    - imagecaster build
    - imagecaster montage
  artifacts:
    paths:
      - README.md
      - LICENSE
      - build/montages/*
      - build/export/*
