image: elypia/imagecaster:0.4.0-q8

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - imagecaster check

build:
  stage: build
  script:
    - imagecaster build
    - imagecaster montage
  artifacts:
    paths:
      - README.md
      - LICENSE
      - build/montages/*
      - build/export/*

pages:
  image: leplusorg/compress
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - mkdir public
    - mv build/montages/* public
    - mv build/export emojis
    - echo '<!DOCTYPE html><html lang="en"><title>Red Panda Emojis</title><meta http-equiv="refresh" content="0; url=&quot;https://sethfalco.gitlab.io/red-panda-emojis/red-panda-emojis.zip&quot;"><body>Downloading red panda emojis…</body></html>' > public/index.html
    - zip -r public/red-panda-emojis.zip README.md LICENSE emojis
  artifacts:
    paths:
      - public
  only:
    - main
